# Generated by Django 5.1.15 on 2026-06-07 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("dataset", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "生成中"), ("success", "成功"), ("failed", "失败")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(blank=True, null=True, verbose_name="行数")),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(blank=True, null=True, verbose_name="大小(字节)"),
                ),
                ("error_msg", models.TextField(blank=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="dataset.dataset",
                        verbose_name="来源数据集",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="catalog.folder",
                        verbose_name="所在文件夹",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据文件",
                "verbose_name_plural": "数据文件",
                "ordering": ["-created_at"],
            },
        ),
    ]
