# Generated by Django 5.1.15 on 2026-06-05 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dataset", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "运行中"), ("success", "成功"), ("failed", "失败")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(blank=True, null=True, verbose_name="行数")),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(blank=True, null=True, verbose_name="文件大小(字节)"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, verbose_name="错误信息")),
                ("is_latest", models.BooleanField(default=False, verbose_name="最新版本")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="dataset.dataset",
                        verbose_name="数据集",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "执行记录",
                "verbose_name_plural": "执行记录",
                "ordering": ["-started_at"],
            },
        ),
    ]
