# Generated by Django 5.1.15 on 2026-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)'),
        ),
    ]
