# Generated by Django 5.1.15 on 2026-06-07 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, verbose_name="账号")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("run", "运行数据集"),
                            ("download", "下载文件"),
                        ],
                        max_length=20,
                        verbose_name="动作",
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=200, verbose_name="对象")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
