# Generated by Django 5.1.15 on 2026-06-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together=set(),
        ),
    ]
