# Generated by Django 5.1.15 on 2026-06-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='requestable',
            field=models.BooleanField(default=False, verbose_name='可被申请'),
        ),
    ]
