# Generated by Django 5.1.15 on 2026-06-05 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="名称")),
                ("host", models.CharField(max_length=200, verbose_name="主机")),
                ("port", models.IntegerField(default=1521, verbose_name="端口")),
                ("service_name", models.CharField(max_length=100, verbose_name="服务名")),
                ("username", models.CharField(max_length=100, verbose_name="账号")),
                ("password_encrypted", models.TextField(blank=True, verbose_name="密码(加密)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源",
                "ordering": ["name"],
            },
        ),
    ]
