# Generated by Django 5.1.15 on 2026-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="db_type",
            field=models.CharField(
                choices=[("oracle", "Oracle"), ("mysql", "MySQL")],
                default="oracle",
                max_length=20,
                verbose_name="类型",
            ),
        ),
    ]
